queue_rules:
  - name: dependabot-pino-nestjs
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - -check-failure~=build-lint-test
      - check-success~=build-lint-test
      - check-success=security/snyk (yamcodes)
    merge_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - -check-failure~=build-lint-test
      - check-success~=build-lint-test
      - check-success=security/snyk (yamcodes)
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
