name: lint
description: "Check linting on pull requests"

on:
  pull_request:
    branches:
      - main

jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Reviewdog (Checks)
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: error
          biome_flags: "--diagnostic-level=error"
      - name: Reviewdog (PR)
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          biome_flags: "--diagnostic-level=error"
